#!/bin/bash

# NOTE: DO NOT CHANGE SCRIPT NAME TO CONTAIN THE SUBSTRING "dropdown_calc"!!!
#
#       This would break the script if you do, because it messes up
#       pgrep's pattern matching. Also, pgrep does not and is not
#       smart enough to take regex as input, so I couldn't fix the
#       pgrep command below.
#

if ! pgrep -f "dropdown_calc" > /dev/null
then
    st -n "dropdown_calc" -e sh -c 'echo "Hint: press Ctrl+L at anytime to clear the screen." && qalc'
fi
