#!/bin/bash

# NOTE: DO NOT CHANGE SCRIPT NAME TO CONTAIN THE SUBSTRING "dropdown_term"!!!
#
#       This would break the script if you do, because it messes up
#       pgrep's pattern matching. Also, pgrep does not and is not
#       smart enough to take regex as input, so I couldn't fix the
#       pgrep command below.
#

if ! pgrep -f "dropdown_term" > /dev/null
then
    st -n "dropdown_term"
fi
